# Dockerfile for FastAPI
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY ./static /app/static

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "4000", "--workers", "4"]
